### ISSUE TITLE
Wrong assignment of some cubic units

### ISSUE THREAD

**Issue by FossoresLP** [frdrk/ulauncher-dead-simple-convert#1]
Hi, I was looking to the supported unit list and found a few units that seem to have been assigned to the wrong unit class.

```python
    "cubic meter":  "in3", #<--------
    "in3":          "in3",
    "inch cube":    "in3",
    "cubic inch":   "in3",
    "ft3":          "ft3",
    "cubic feet":   "in3", #<--------
```

`cubic meter` should probably be `m3` and `cubic feet` should probably be `ft3`.

**Comment by frdrk** [comment]
Hey, 
You are absolutely right. I'll get those sorted and push the changes asap.
Thanks!

**Comment by frdrk** [comment]
Done.
